### ISSUE TITLE
Can't figure out exclude

### ISSUE THREAD

**Issue by Ben1nBlack** [lujiaying/FTP-Deploy-Action-Py3.9#1]
Please Help.
I'm running out of Market place FTP action, None follow exclude param work :-(

I have tried
          exclude: .git/*,*.env,img/*,images/*
          exclude: .git/*,*.env,img/*,images/*

`INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/loading.gif
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/forward_enabled.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-5_r1_c5.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-5_r2_c3.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/768_header.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-9_r2_c3.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-7_r4_c3.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/10PercentSlider.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/sort_both.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/add_to_cart.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/990_header.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/CF-title.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/CFSnow_Med.gif
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/free-shipping.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-7_r1_c2.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/10-discount-2.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/480_header_landscape.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/1170_checkout.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/my_account_help_mob.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-4_r1_c2.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/forward_disabled.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-5_r3_c3.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/controls.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/back_disabled.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/320_header_portrait.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/login.png
INFO:pyftpsync:(DRY-RUN) COPY MODIFIED     >  images/concept-9_r3_c3.png
`

yaml file contents
`on:
  push:
    branches: [demo]

name: 🚀 Deploy on push - Python

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyftpsync==4.0.0a3
      - name: FTP Deploy
        uses: lujiaying/FTP-Deploy-Action-Py3.9@v1.0
        with:
          host: ${{ secrets.CF_FTP_SERVER }}
          user: ${{ secrets.CF_FTP_USER_NAME }}
          passwd: ${{ secrets.CF_FTP_USER_PASS }}
          port: 21
          local_dir: ./
          remote_dir: /demo
          exclude: .git/*,*.env,img/,images/,Backups/,logs/,ups2csv/,Witango5Admin/,CFSITEMAP-ALPHA_files/,CFSITEMAP_files/,/aspnet_client/
          dry_run: True
`

**Comment by lujiaying** [comment]
Hi,

could you try the following arguments
`exclude: imgs,images`

Basically, we don't need to specify the `/` for dirctories.
Reference: https://pyftpsync.readthedocs.io/en/latest/ug_cli.html
