### ISSUE TITLE
File path 

### ISSUE THREAD

**Issue by XessiveObserver** [lujiaying/FTP-Deploy-Action-Py3.9#2]
The file path ... Place the following scripts in ./.github/workflows/main,yml is missing a dot for main.yml

**Comment by lujiaying** [comment]
My bad. Thanks for the clarification. 

Fixed in [4c0c82a](https://github.com/lujiaying/FTP-Deploy-Action-Python/commit/4c0c82af057c29bd2b0e0a897b5e892c6d86b650)

**Comment by XessiveObserver** [comment]
It's a great tool  🙂 for CI/CD
